apiVersion: v1
appVersion: "1.12.3"
description: Allow cert-manager to solve DNS challenges using Oracle Cloud Infrastructure DNS
name: cert-manager-webhook-oci
version: "1.4.0"
icon: https://www.oracle.com/asset/web/favicons/favicon-32.png
